### ISSUE TITLE
Create test endpoint

### ISSUE THREAD

**Issue by bertspaan** [histograph/neo4j-plugin#5]
Create test endpoint (for example on `/histograph/test`) which always returns simple string.

**Comment by wires** [comment]
> On 12 Aug 2015, at 17:03, Bert Spaan notifications@github.com wrote:
> 
> Create test endpoint (for example on `/histograph/test') which always returns simple string.

may i suggest `/ping` that responds to `pong`

`app.get('/ping', function(req, res) { res.end(‘pong’) } )`
 hahajavarrrrgh
