### ISSUE TITLE
latest neo4j-plugin Jar stops neo4j from starting

### ISSUE THREAD

**Issue by ghost** [histograph/neo4j-plugin#8]
ubuntu 12.04 and 14.10, neo4j stable, neo4j-plugin from https://github.com/histograph/neo4j-plugin/blob/master/dist/histograph-plugin-0.5.0-SNAPSHOT.jar causes neo4j-service to report success but actually fail to start, with following log messages: 

Sep 21, 2015 3:31:19 PM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  org.waag.histograph.plugins
Sep 21, 2015 3:31:20 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
Sep 21, 2015 3:31:21 PM com.sun.jersey.server.impl.application.RootResourceUriRules <init>
SEVERE: The ResourceConfig instance does not contain any root resource classes.

If I use the jar from the [previous commit](https://github.com/histograph/neo4j-plugin/tree/8b9dd33a99bccbfbaf219617480bb3e0ddfe0b99/dist) it does succeed in starting and the plugin loads successfully.

**Comment by ghost** [comment]
hmm, but with this version/setup I get the 'neo4j plugin returned incorrect JSON data' error if I search for a PiT that DOES exist.

**Comment by ghost** [comment]
I built neo4j-plugin from source@master, it works and API returns results now ...

**Comment by wires** [comment]
Hm, wonder what happened there, thanks for reporting this, I'll look into it!

**Comment by jobspierings** [comment]
Can we close this issue?

**Comment by ghost** [comment]
As far as I'm concerned, yes.
