### ISSUE TITLE
Sort by ES hits per concept / PITs per concept

### ISSUE THREAD

**Issue by bertspaan** [histograph/neo4j-plugin#9]
Sort by ES hits per concept / PITs per concept.

(Or, even better: sort by ES hits \* ES score per concept / PITs per concept: #10)

**Comment by jobspierings** [comment]
@bertspaan compare this one w/ #10 and [API #21](https://github.com/histograph/api/issues/21) - is this related to any specific user request/bug? 

If not we can close this for now, and reopen if neccessary. If best solution for sorting results is clear please advice.

**Comment by bertspaan** [comment]
Please leave open. This seems still to be best solution. Why this urge to close as many issues as possible?

**Comment by sbocconi** [comment]
Can I close this as duplicate of #10 which is better explained?

**Comment by bertspaan** [comment]
Ok!

**Comment by sbocconi** [comment]
Duplicates #10
